apiVersion: v1
kind: Pod
metadata: 
  name: kube-controller
spec: 
  hostNetwork: true
  containers: 
    - name: "etcd"
      image: "b.gcr.io/kuar/etcd:2.1.1"
      args: 
        - "--data-dir=/var/lib/etcd"
        - "--advertise-client-urls=http://127.0.0.1:2379"
        - "--listen-client-urls=http://127.0.0.1:2379"
        - "--listen-peer-urls=http://127.0.0.1:2380"
        - "--name=etcd"
    - name: "kube-apiserver"
      image: "gcr.io/google_containers/hyperkube:v1.0.3"
      args: 
        - "/hyperkube"
        - "apiserver"
        - "--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"
        - "--authorization-mode=ABAC"
        - "--authorization-policy-file=/etc/kubernetes/policy.jsonl"
        - "--etcd-servers=http://127.0.0.1:2379"
        - "--insecure-bind-address=0.0.0.0"
        - "--service-cluster-ip-range=10.200.20.0/24"
        - "--v=2"
        - "--tls-cert-file=/var/run/kubernetes/apiserver/cert.pem"
        - "--tls-private-key-file=/var/run/kubernetes/apiserver/key.pem"
        - "--secure-port=6443"
        - "--insecure-port=8080"
    - name: "kube-controller-manager"
      image: "gcr.io/google_containers/hyperkube:v1.0.3"
      args: 
        - "/hyperkube"
        - "controller-manager"
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-scheduler"
      image: "gcr.io/google_containers/hyperkube:v1.0.3"
      args:
        - "/hyperkube"
        - "scheduler"
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-proxy"
      image: "gcr.io/google_containers/hyperkube:v1.0.3"
      args:
        - "/hyperkube"
        - "proxy"
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
      users:
        - name: proxy
          user:
             client-certificate: /var/run/kubernetes/proxyserver/cert.pem
             client-key: /var/run/kubernetes/proxyserver/key.pem
      securityContext:
        privileged: true
